version: "3.8"
services:
 mariadb:
    image: mariadb:10.7
    container_name: mariadb_glpi
    environment:
      - MYSQL_ROOT_PASSWORD=rmqiBzyfx5rH
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpiliis
      - MYSQL_PASSWORD=QJR2WEEljf3S
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
